name: flutter_inset_box_shadow_update
description: This package extends BoxShadow and BoxDecoration to support the inset property.
version: 0.0.1
repository: https://github.com/qoumo/flutter_inset_box_shadow

dependencies:
  flutter:
    sdk: flutter
environment:
  sdk: ^3.8.1
